[build]
  publish   = "."
  functions = "netlify/functions"

# Redirect form submission endpoint
[[redirects]]
  from   = "/.netlify/functions/*"
  to     = "/.netlify/functions/:splat"
  status = 200
